### PR TITLE
Fixed #541

### LINKED ISSUE #541: [Bug]: The dependencies under a project card are not linked to their respective project card page.
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://be-secure.github.io/Be-Secure/contribute.html) and wholeheartedly agree

### Description

The dependencies under any project card, should take the user to their corresponding project card.

### Expected behaviour

When clicking on each dependency, the user should be taken to their respective project card.

### Actual behaviour

Only displaying dependencies.

### Steps to reproduce

NA

### Relevant screenshots

NA

### What browsers are you seeing the problem on?

Microsoft Edge

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by asa1997**
Fix #541

### CODE REVIEW

File: src/pages/BesVersionHistory/AssessmentReport/index.tsx [hunk 1]
```diff
@@ -667,14 +667,18 @@ const FetchSBOM = ({data, masterData, name}: any) => {
...
+          });
 
         if (!duplicate)
           tracked.push(dp.name);
       }
     });
   });
-  dis = tracked.map(function (td: string, index: number) {
+    dis = tracked.map(function (td: string, index: number) {
+    var dataObject = masterData.find(function(item){
```
Comment (sudhirverma) [inline src/pages/BesVersionHistory/AssessmentReport/index.tsx:678]: can you use const here

File: src/pages/BesVersionHistory/AssessmentReport/index.tsx [hunk 2]
```diff
@@ -667,14 +667,18 @@ const FetchSBOM = ({data, masterData, name}: any) => {
...
+      return item.name == td
+    })
+    var trackingID = dataObject.id
```
Comment (sudhirverma) [inline src/pages/BesVersionHistory/AssessmentReport/index.tsx:681]: same here
