### PR TITLE
Fixed #567 #542

### LINKED ISSUE #542: [Bug]: Inconsistency between Risk posture graph and SAST Summary - Skywalking
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://be-secure.github.io/Be-Secure/contribute.html) and wholeheartedly agree

### Description

The risk posture graph depicts data while no data exists for SAST summary for the Skywalking project

### Expected behaviour

The risk posture graph should be the exact graphical representation of the SAST summary data. 

### Actual behaviour

No data exists for SAST summary but the risk posture graph indicates 50% High and 50% medium vulnerabilities

### Steps to reproduce

Can be viewed from the project details page for Skywalking version 9.5.0

### Relevant screenshots

Will upload later

### What browsers are you seeing the problem on?

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #567: [Bug]: SAST summary card does not get updated when the data is not available while we switch the version.
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://be-secure.github.io/Be-Secure/contribute.html) and wholeheartedly agree

### Description

Assume two versions (a  and b) are being tracked for a project and there is no sast data available for version "b".  The sast card doesnt get updated when we switch versions from "a" to "b".

### Expected behaviour

Should display "Not Available" if the report is not available for other versions.

### Actual behaviour

Displays the data for the version for which SAST is available even when we switch to a version for which the SAST data is not available.

### Steps to reproduce

1. Go to fastjson under project card.
2. switch version to 1.2.83.
3. You can see that the sast data being displayed is for 1.2.24 eventhough sast report is not available for 1.2.83

### Relevant screenshots

image
image

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by asa1997**
Fix #567 
Fix #542

### CODE REVIEW

File: src/pages/BesVersionHistory/AssessmentReport/index.tsx [hunk 1]
```diff
@@ -1008,6 +1018,23 @@ const GetAssessmentData = ({ version, name, report, itemData, masterData }: any)
       </>
     );
   }
+  // If SAST report is not available
+  else if (report === "Vulnerabilities" && (JSON.stringify(Object.values(codeQlData).length) == "0" &&
+    JSON.stringify(Object.values(sonarqubeData).length) == "0")) {
+      return(
+        <>
```
Comment (sudhirverma) [inline src/pages/BesVersionHistory/AssessmentReport/index.tsx:1025]: you can remove this.

Comment (asa1997) [reply src/pages/BesVersionHistory/AssessmentReport/index.tsx]: Done

**Review by sudhirverma — APPROVED** [review]
